const { v4: uuid } = require("uuid");
const { query } = require("../database");

const CATEGORIES=["DESIGN","CLEANING","SECURITY","TECHNICAL","DECORATION","CATERING","ELECTRICAL","MAINTENANCE","PHOTOGRAPHY","SEATING","OTHER"];
function toService(r){if(!r)return null;return{id:r.id,venueId:r.venue_id,venueName:r.venue_name,name:r.name,category:r.category,providerName:r.provider_name,role:r.role,phone:r.phone,email:r.email,contractRef:r.contract_ref,contractStart:r.contract_start?String(r.contract_start).slice(0,10):"",contractEnd:r.contract_end?String(r.contract_end).slice(0,10):"",rate:Number(r.rate||0),billingUnit:r.billing_unit,scope:r.scope,status:r.status,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at};}
async function list({venueId="",status="",category="",ownerId=""}={}){const w=[];const p=[];if(venueId){p.push(venueId);w.push(`s.venue_id=$${p.length}`)}if(status){p.push(status);w.push(`s.status=$${p.length}`)}if(category){p.push(category);w.push(`s.category=$${p.length}`)}if(ownerId){p.push(ownerId);w.push(`v.owner_id=$${p.length}`)}const c=w.length?`WHERE ${w.join(" AND ")}`:"";const{rows}=await query(`SELECT s.*,v.name AS venue_name FROM venue_services s JOIN venues v ON v.id=s.venue_id ${c} ORDER BY s.category,s.provider_name,s.name`,p);return rows.map(toService);}
async function findById(id){const{rows}=await query(`SELECT s.*,v.name AS venue_name FROM venue_services s JOIN venues v ON v.id=s.venue_id WHERE s.id=$1`,[id]);return toService(rows[0]);}
async function create(d){const id=uuid();const{rows}=await query(`INSERT INTO venue_services (id,venue_id,name,category,provider_name,role,phone,email,contract_ref,contract_start,contract_end,rate,billing_unit,scope,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[id,d.venueId,d.name.trim(),d.category,d.providerName.trim(),(d.role||"").trim(),(d.phone||"").trim(),(d.email||"").trim(),(d.contractRef||"").trim(),d.contractStart||null,d.contractEnd||null,Number(d.rate||0),(d.billingUnit||"event").trim(),(d.scope||"").trim(),d.status||"ACTIVE",(d.notes||"").trim()]);return toService({...rows[0],venue_name:(await query("SELECT name FROM venues WHERE id=$1",[d.venueId])).rows[0]?.name});}
async function update(id,data){const m={name:"name",category:"category",providerName:"provider_name",role:"role",phone:"phone",email:"email",contractRef:"contract_ref",contractStart:"contract_start",contractEnd:"contract_end",rate:"rate",billingUnit:"billing_unit",scope:"scope",status:"status",notes:"notes"};const sets=[];const p=[];for(const[k,c]of Object.entries(m)){if(data[k]!==undefined){p.push(k==='rate'?Number(data[k]||0):data[k]);sets.push(`${c}=$${p.length}`)}}if(!sets.length)return findById(id);p.push(id);const{rows}=await query(`UPDATE venue_services SET ${sets.join(",")},updated_at=now() WHERE id=$${p.length} RETURNING *`,p);const row=rows[0];if(!row)return null;const vn=await query("SELECT name FROM venues WHERE id=$1",[row.venue_id]);return toService({...row,venue_name:vn.rows[0]?.name});}
async function remove(id){const r=await query("DELETE FROM venue_services WHERE id=$1",[id]);return r.rowCount>0;}
async function attachToBooking(bookingId, serviceIds=[], startsAt, endsAt, client){const ids=[...new Set(serviceIds)].filter(Boolean);if(!ids.length)return[];const now=new Date().toISOString();for(const sid of ids){const s=await findById(sid);if(!s)continue;await query(`INSERT INTO booking_services (id,booking_id,service_id,quantity,agreed_rate,notes,starts_at,ends_at,created_at) VALUES ($1,$2,$3,1,$4,'',$5,$6,$7) ON CONFLICT (booking_id,service_id) DO NOTHING`,[uuid(),bookingId,s.id,s.rate,startsAt,endsAt,now],client);}return getForBooking(bookingId,client);}
async function getForBooking(bookingId,client){
  try {
    const {rows}=await query(`SELECT bs.*,s.name,s.category,s.provider_name,s.role,s.phone,s.email,s.contract_ref,s.contract_start,s.contract_end,s.rate,s.billing_unit,s.scope,s.status FROM booking_services bs LEFT JOIN venue_services s ON s.id=bs.service_id WHERE bs.booking_id=$1 ORDER BY COALESCE(s.category, ''),COALESCE(s.provider_name, ''),COALESCE(s.name, '')`,[bookingId],client);
    return rows.map(r=>({id:r.service_id,bookingServiceId:r.id,name:r.name||"Service",category:r.category||"OTHER",providerName:r.provider_name||"",role:r.role||"",phone:r.phone||"",email:r.email||"",contractRef:r.contract_ref||"",contractStart:r.contract_start?String(r.contract_start).slice(0,10):"",contractEnd:r.contract_end?String(r.contract_end).slice(0,10):"",rate:Number(r.rate||0),agreedRate:Number(r.agreed_rate||0),billingUnit:r.billing_unit||"event",scope:r.scope||"",status:r.status||"ACTIVE",quantity:Number(r.quantity||1),notes:r.notes||""}));
  } catch (error) {
    // Services are optional enrichment for bookings. Never make the dashboard unusable
    // because an older database is missing an optional service table/column.
    console.warn("[services] Optional service data unavailable; returning empty service list.", error?.code || "unknown", error?.message || error);
    return [];
  }
}
module.exports={CATEGORIES,list,findById,create,update,remove,ownerOfVenue:async(venueId)=>{const{rows}=await query("SELECT owner_id FROM venues WHERE id=$1",[venueId]);return rows[0]?.owner_id||null;},attachToBooking,getForBooking};
